In [70]:
import pandas as pd 
import numpy as np

In [71]:
# Importing data 
data=pd.read_csv("Employee_data.csv")

# Exploratory Data Analysis(EDA)

In [72]:
# Getting sample of data 
data.head()

             Name   Age  Gender   Salary  Department JoiningDate
0     Amit Sharma  28.0    Male  45000.0          IT  15-06-2021
1     Priya Verma  32.0  Female  52000.0          HR  10-03-2019
2     Rahul Patil  26.0    Male  40000.0          IT  12-01-2022
3  Sneha Kulkarni  30.0     NaN  48000.0     Finance  22-07-2020
4     Vikas Singh  35.0    Male  65000.0  Operations  18-09-2018

In [73]:
# Now we have 2 types of variable 
# 1:-Categorical variable(Gender,Department,Date)
# 2:-Quatitative variable(Age,Salary)

In [74]:
# Let's check the size of database 
data.shape

(52, 6)

In [75]:
# So we have 50 rows and 6 columns

# • Handle missing values using two different techniques

In [76]:
# • Handle missing values using two different techniques
# ANS:- 

# let's find the missing values 
data.isnull().sum()

Name           0
Age            2
Gender         2
Salary         2
Department     0
JoiningDate    0
dtype: int64

In [77]:
# We have the following missing value
# Age            2 missing
# Gender         2 missing
# Salary         2 missing

In [78]:
# Let's handle each individualy
# 1.Missing values in Age 
# :-
# let check the missing values 
data[data.isnull().any(axis=1)]

              Name   Age  Gender   Salary  Department JoiningDate
3   Sneha Kulkarni  30.0     NaN  48000.0     Finance  22-07-2020
9      Anjali Nair  24.0  Female      NaN   Marketing  25-08-2022
10      Karan Shah  36.0     NaN  70000.0  Operations  30-05-2016
15     Tanvi Patil   NaN  Female  54000.0   Marketing  12-06-2019
18    Manish Yadav  30.0    Male      NaN          IT  20-02-2020
23    Komal Bansal   NaN  Female  45000.0          HR  11-12-2020

In [79]:
# As we can see above there are 2 missing values which shows NaN 
# So we can either remove or replace the values but i would choose to replace it because we have small dataset so removing entire column
# can effect the model performace so i gonna replace it with mean of the the all ages this will disolve the in the dataset and it will not effect my ML model

In [80]:
data['Age']=data['Age'].fillna(data['Age'].mean())

In [81]:
# let see missing age replaced or not 
data.isnull().sum()

Name           0
Age            0
Gender         2
Salary         2
Department     0
JoiningDate    0
dtype: int64

In [82]:
# As we can see above values has been replaced with mean 
# let's take gender
data[data.isnull().any(axis=1)]

              Name   Age  Gender   Salary  Department JoiningDate
3   Sneha Kulkarni  30.0     NaN  48000.0     Finance  22-07-2020
9      Anjali Nair  24.0  Female      NaN   Marketing  25-08-2022
10      Karan Shah  36.0     NaN  70000.0  Operations  30-05-2016
18    Manish Yadav  30.0    Male      NaN          IT  20-02-2020

In [83]:
# since gender is in binary value and in text it is not possible to calculate mean so can use Mode(most freq occuring value) but it is random and it will change the shape of data distribution so  i'll apply feature enginnering 
#  feature engineering the process of the applying bussiness knowledge and getting the most aproximate data to train the model.
# We can see that in Gender's missing value  we have name so we can deteremine the gender using name

# I below row i can clearly see that name of employee is sneha so it is likely that she is Female 
# 3	Sneha Kulkarni	30.0	NaN	48000.0	Finance	22-07-2020

# I below row i can clearly see that name of employee is sneha so it is likely that she is male 
# 10	Karan Shah	36.0	NaN	70000.0	Operations	30-05-2016

# So at the end i will repplace the Sneha's gender with female and Karan's gender with the male

In [84]:
data.loc[data['Name'] == 'Sneha Kulkarni', 'Gender'] = 'Female'
data.loc[data['Name'] == 'Karan Shah', 'Gender'] = 'male'

In [85]:
data.isnull().sum()

Name           0
Age            0
Gender         0
Salary         2
Department     0
JoiningDate    0
dtype: int64

In [86]:
# As we can see that above we have only salary column with missing value
data[data.isnull().any(axis=1)]

            Name   Age  Gender  Salary Department JoiningDate
9    Anjali Nair  24.0  Female     NaN  Marketing  25-08-2022
18  Manish Yadav  30.0    Male     NaN         IT  20-02-2020

In [87]:
# I'll use the same method i've used on the age column our main goal is to keep data in the dataset to make data consistency but at the same time model accuracy . 
# let's replace missing salary with the mean of all saries 
data['Salary']=data['Salary'].fillna(data['Salary'].mean())

In [88]:
# let's see if there's any other missing values 
data.isnull().sum()

Name           0
Age            0
Gender         0
Salary         0
Department     0
JoiningDate    0
dtype: int64

# • Remove duplicates

In [95]:
# let's check is there's any duplicate value 
data.duplicated().sum()

np.int64(2)

In [96]:
# So we have 2 duplicated values *
# * finding duplicated values is Subjective I am using .duplicated method because i have small dataset

In [99]:
# let's remove the duplicated values
data=data.drop_duplicates()

In [102]:
data.duplicated().sum()

np.int64(0)

In [103]:
# So we have the 0 duplicated values

# • Detect outliers using IQR method

In [111]:
data.head()

             Name   Age  Gender   Salary  Department JoiningDate
0     Amit Sharma  28.0    Male  45000.0          IT  15-06-2021
1     Priya Verma  32.0  Female  52000.0          HR  10-03-2019
2     Rahul Patil  26.0    Male  40000.0          IT  12-01-2022
3  Sneha Kulkarni  30.0  Female  48000.0     Finance  22-07-2020
4     Vikas Singh  35.0    Male  65000.0  Operations  18-09-2018

In [113]:
# To check outlier so we can only check quatitative values such as (Age, Salary) 
# Outliers are extreme most or least value it depend on the dataset 
# :-
# formula to calculate outlier using IQR is IQR(Inter Quartile Range) =Q3-Q1 so we have calculate quantile 

# Step-1:- Calculate Quantiles 
# Step-2:- Putting them in the formula 
# Step-3:- calculating lower and upper bound 
# Step-4:- declaring value below lower bound is outlier and value high than upper bound

In [118]:
# checking outlier for age 
Q1=data['Age'].quantile(0.25)
Q3=data['Age'].quantile(0.75)

IQR=Q3-Q1 
lower_bound=Q1-1.5*IQR 
upper_bound=Q3+1.5*IQR

outliers = data[(data['Age'] < lower_bound) | (data['Age'] > upper_bound)]
outliers

Empty DataFrame
Columns: [Name, Age, Gender, Salary, Department, JoiningDate]
Index: []

# • Convert JoiningDate to datetime format

In [119]:
# let's check type of the joining date

In [123]:
print(data['JoiningDate'].dtype)

object

In [124]:
# Datatype is object let's convert it into the datetime 
data['JoiningDate']=pd.to_datetime(data['JoiningDate'])

C:\Users\sonu_\AppData\Local\Temp\ipykernel_18488\1061866890.py:2: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  data['JoiningDate']=pd.to_datetime(data['JoiningDate'])

In [125]:
print(data['JoiningDate'].dtype)

datetime64[ns]

In [126]:
data['JoiningDate']

0    2021-06-15
1    2019-03-10
2    2022-01-12
3    2020-07-22
4    2018-09-18
5    2021-11-05
6    2019-12-01
7    2023-02-14
8    2017-04-19
9    2022-08-25
10   2016-05-30
11   2020-10-10
12   2018-01-15
13   2021-04-17
14   2023-03-21
15   2019-06-12
16   2015-11-09
17   2022-05-03
18   2020-02-20
19   2018-07-14
20   2021-09-28
21   2023-01-07
22   2019-08-19
23   2020-12-11
24   2016-03-05
25   2022-04-22
26   2017-10-30
27   2019-02-18
28   2023-06-01
29   2020-09-09
30   2018-06-16
31   2021-07-27
32   2022-03-15
33   2019-05-23
34   2023-02-02
35   2020-11-18
36   2018-04-12
37   2022-09-05
38   2016-12-20
39   2021-01-14
40   2019-10-08
41   2023-07-19
42   2017-03-11
43   2020-06-29
44   2022-02-25
45   2019-09-17
46   2018-08-04
47   2021-12-13
48   2017-01-26
49   2023-05-10
Name: JoiningDate, dtype: datetime64[ns]

# • Encode categorical columns

In [ ]:
# I need to practice more

# • Perform groupby aggregation (average salary per department)

In [ ]:
# Purpose of the calculating department wise salary could be reviewing expediture and comparing with performance now it depend on the bussiness requrements.

In [110]:
data.groupby('Department')["Salary"].mean()

Department
Finance       53000.000000
HR            47800.000000
IT            47376.923077
Marketing     48322.222222
Operations    67375.000000
Name: Salary, dtype: float64

In [ ]:
cleaned_data = data.to_csv("cleaned_data.csv", index=False)